<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
		<UserSecretsId>439b0f41-6f6e-4b13-b0e0-6962dae586ac</UserSecretsId>
		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.ApplicationInsights" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ContainerPort Include="8081" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\aspire\ShowRoom.ServiceDefaults\ShowRoom.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\..\modules\ShowRoom.Modules.Product\ShowRoom.Modules.Product.csproj" />
	  <ProjectReference Include="..\..\modules\ShowRoom.Modules.Customer\ShowRoom.Modules.Customer.csproj" />
	  <ProjectReference Include="..\..\modules\ShowRoom.Modules.Order\ShowRoom.Modules.Order.csproj" />
	</ItemGroup>

</Project>
