using Meziantou.Framework.Annotations;

namespace ShowRoom.Modules.Customer.Domain;

/// <summary>
/// Strongly-typed technical identifier of a customer, generated by Meziantou. Used internally within
/// the domain and persistence layers only; never exposed over HTTP (only <c>PublicId</c> is).
/// </summary>
[StronglyTypedId(typeof(Guid))]
public partial struct CustomerId : IComparable { }