using Meziantou.Framework.Annotations;

namespace ShowRoom.Modules.Order.Domain;

/// <summary>
/// Strongly-typed technical identifier of an order line, generated by Meziantou. Internal to the
/// Order aggregate; order lines are never addressed directly over HTTP.
/// </summary>
[StronglyTypedId(typeof(Guid))]
public partial struct OrderLineId : IComparable { }
