using Meziantou.Framework.Annotations;

namespace ShowRoom.Modules.Order.Domain;

/// <summary>
/// Strongly-typed technical identifier of an order, generated by Meziantou. Used internally within
/// the domain and persistence layers only; never exposed over HTTP (only <c>PublicId</c> is).
/// </summary>
[StronglyTypedId(typeof(Guid))]
public partial struct OrderId : IComparable { }
